### ISSUE TITLE
Define formalization of simulated pod spec

### ISSUE THREAD

**Issue by ordovicia** [ordovicia/virtual-kubelet#13]
Temporarily specified by embedding a JSON string as an annotation.

```yaml
metadata:
  name: nginx-sim
  annotations:
    simSpec: "[{\"seconds\":5,\"cpu\":\"1\",\"memory\":\"2Gi\",\"nvidia.com/gpu\":0},{\"seconds\":10,\"cpu\":\"2\",\"memory\":\"4Gi\",\"nvidia.com/gpu\":1}]"
```

- [x] Deterministic
- [ ] Probabilistic
